### PR TITLE
Added information about generators #45

### PR DESCRIPTION
**Pull request by vidban**
In response to Issue #45

### CODE REVIEW

**Comment by leonardomso** [comment]
Well, since the repo name is "33 concepts" I don't think that makes any sense we put the 34th concept. Instead, I think that we could add some info about Generators with the Collections section, would end up something like "Collections and Generators". What do you think?

**Comment by vidban** [comment]
Oops! I should've seen that! haha

I apologize. 

I will modify it and add it to collections and change the title to `Collections and Generators`.

**Comment by JessevanAssen** [comment]
Instead of moving the information from `Generators` to `Collections and Generators`, you copied it, so concept 34 still exists (although it is not included in the table of contents).

**Comment by leonardomso** [comment]
Yes, you're right, I'm gonna fix it! Thanks @JessevanAssen

**Pull request merged**
